version: '3'

services:
  mongo:
    container_name: cr-mongo
    image: mongo:5.0.14
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
      - ./backup:/backup

  mongo-express:
    image: mongo-express:0.54.0
    restart: unless-stopped
    env_file: .env
    ports:
      - 8081:8081
    depends_on:
      - mongo

  dind-cron:
    build: .docker/dind-cron
    restart: unless-stopped
    env_file: .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mongo_configdb:
  mongo_db:
