version: '3'

services:
  mongo:
    container_name: cr-mongo
    image: mongo:6.0.3
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
      - ./backup:/backup

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  dind-cron:
    build: .docker/dind-cron
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mongo_configdb:
  mongo_db:
